### ISSUE TITLE
Good Reads

### ISSUE THREAD

**Issue by jbenet** [ipfs/community#134] opened 2016-06-17 02:30 UTC
Let's collect some links for protocol engineering.

**Comment by jbenet** [comment] 2016-06-17 02:31
- https://www.nanog.org/sites/default/files/Paasch_Network_Support.pdf on TCP Fast Open and the experiences with real deployment. Curse the middleboxes.

**Comment by RichardLitt** [comment] 2016-06-17 10:21
Possible duplicate of https://github.com/ipfs/ipfs/pull/24.

**Comment by pawal** [comment] 2016-09-26 10:15
[RFC 5218](https://tools.ietf.org/html/rfc5218), "What Makes for a Successful Protocol?".

**Comment by diasdavid** [comment] 2017-04-12 08:14
-> https://github.com/ipfs/reading-list

**Closed by diasdavid** 2017-04-12 08:14 UTC
