### ISSUE TITLE
Doubts about how to start to contribute

### ISSUE THREAD

**Issue by ggarri** [ipfs/community#450] opened 2020-01-01 20:14 UTC
Hi @ipfs Team, I am a software engineer with more than 5 years experiences coding in NodeJS. During past year at my current company I have been experimenting with IPFS project and implementing some small projects around it. I got very excited about this project and its potential growth, especially for the js version of it and I would like to collaborate with it,

I already went thought your [CONTRIBUTING](https://github.com/ipfs/community/blob/master/CONTRIBUTING_JS.md) docs and other community pages but I am uncertain if I should request permission before I start or I should just jump in a take an issue I can understand. Could you help me with it?

I am currently looking for a first easy issue to work on, do you think [this one](https://github.com/ipfs/js-ipfs/issues/2667) is a good start ? ( @hugomrdias  )

**Comment by momack2** [comment] 2020-01-04 03:19
You can definitely hop into an issue you think you have an idea on, propose your implementation path, and then PR a solution. That one seems fine to me, though @hugomrdias, @alanshaw or @achingbrain can best comment to complexity. Thanks for jumping in to help!!

**Comment by alanshaw** [comment] 2020-01-04 07:56
Yes, that one is a good start! Issues labelled with “help wanted” are also good starting points. We also label according to perceived difficulty (although be aware that it’s an estimate!).

As with any OSS project it’s a good idea to ping to say you’re working on a thing, it’ll prevent multiple people working on the same issue and gives us the opportunity to refocus you if the issue is stale or has become very low priority.

If you have any observations for how to make starting to contribute easier then I’d love to hear them. Also, PRs welcome 😁

**Comment by johnnymatthews** [comment] 2020-01-06 15:55
Yet again the community is one step ahead of my commits. Over the winter break I've been putting a walkthrough guide called _How to actually contribute to the project_. In the guide I walk users through:

1. Finding an issue.
2. Discussing the issue.
3. Creating a fix.
4. Submitting a _pull request_.
5. Waiting for a review.
6. Merging your fix.

I've been writing it specifically for the [`ipfs/docs` project](https://github.com/ipfs/docs) but it can easily be modified to fit other projects. The guide should be complete by the end of this week.

If you're up for it @ggarri I'd be happy to work with you in editing the contribution walkthrough to fit other projects like this one?

**Comment by hsanjuan** [comment] 2020-03-20 17:54
Closing as there was no follow-up here. Feel free to re-open as needed.

**Closed by hsanjuan** 2020-03-20 17:54 UTC
